services:

    postal_code_backend:
        restart: "on-failure"
        image: mx_postal_codes/backend
        build:
            context: ./backend
        expose:
            - 8888
        volumes:
            - ./backend:/app
        environment:
            - SECRET_KEY=django-insecure--jcq!c)sg_v!=d+1ue61h4sf2dc@db^o64kcy^kqp19xz5mj0h
            - POSTGRES_NAME=${POSTGRES_NAME}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
        command: 'gunicorn --bind :8888 backend.wsgi'
    
        
    postal_code_redis:
        image: redis:7
        restart: "on-failure"
        ports:
            - 6380:6379
