# Generated by Django 4.2 on 2024-03-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastModifyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modify', models.CharField(max_length=30)),
                ('identifier', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
